#!/bin/bash

export GRML_FAI_CONFIG=$(pwd)/config
export SCRIPTS_DIRECTORY=$(pwd)/scripts
export LIVE_CONF=$(pwd)/etc/grml/grml-live.conf
export TEMPLATE_DIRECTORY=$(pwd)/templates
export DISTRI_NAME="grml-custom"

./grml-live -g grml-custom -r grml-custom -A -D $(pwd)/config -t $(pwd)/templates -c GRMLBASE,AMD64,COMP,OVERRIDE_GRML
