#!/bin/bash

set -u
set -e

# FAI sets $target, but shellcheck does not know that.
target=${target:?}

# shellcheck source=/dev/null
. "$GRML_LIVE_CONFIG"

# Instala NetBeans y limpia

echo "  [I] COMP: Se copia paquete de NetBeans a chroot."
cp ./netbeans.deb "$target"
$ROOTCMD chown root:root netbeans.deb

$ROOTCMD apt install ./netbeans.deb
$ROOTCMD apt clean
$ROOTCMD rm netbeans.deb
$ROOTCMD apt remove curl -y
$ROOTCMD apt autoremove -y

# Copia las extensiones al chroot, las instala y limpia

if [[ $(ifclass VEXT) ]]; then
	echo "  [I] COMP: Se instalarán las extensiones de VS Code."
	$ROOTCMD mkdir /home/grml/exts
	cp ./extensiones/* "$target"/home/grml/exts
	$ROOTCMD chown -R root:root /home/grml/exts

	INSTALL="--user-data-dir /home/grml/.vscode --no-sandbox --extensions-dir /home/grml/.vscode/extensions --install-extension"

	$ROOTCMD find /home/grml/exts -iname '*.vsix' -exec code $INSTALL {} \;
	$ROOTCMD rm -rf /home/grml/exts
fi
